// Mobile Menu Toggle
const hamburger = document.querySelector(".hamburger");
const navLinks = document.querySelector(".nav-links");

if (hamburger) {
    hamburger.addEventListener("click", () => {
        hamburger.classList.toggle("active");
        navLinks.classList.toggle("active");
    });

    // Close mobile menu when clicking a link
    document.querySelectorAll(".nav-links a").forEach(n => n.addEventListener("click", () => {
        hamburger.classList.remove("active");
        navLinks.classList.remove("active");
    }));
}

// Navbar scroll and hide/show logic
let lastScrollY = window.scrollY;
const header = document.querySelector("header");

window.addEventListener("scroll", () => {
    if (!header) return;
    const currentScrollY = window.scrollY;

    // Show/Hide logic
    if (currentScrollY > lastScrollY && currentScrollY > 100) {
        header.classList.add("nav-hidden");
    } else {
        header.classList.remove("nav-hidden");
    }

    // Background and padding logic
    if (currentScrollY > 50) {
        header.style.padding = "0.5rem 0";
        header.style.background = "rgba(255, 255, 255, 0.95)";
    } else {
        header.style.padding = "1rem 0";
        header.style.background = "rgba(255, 255, 255, 0.8)";
    }

    lastScrollY = currentScrollY;
});

// Scroll Reveal Animation
const observerOptions = {
    threshold: 0.1
};

const observer = new IntersectionObserver((entries) => {
    entries.forEach(entry => {
        if (entry.isIntersecting) {
            entry.target.classList.add("fade-in");
            observer.unobserve(entry.target);
        }
    });
}, observerOptions);

document.querySelectorAll(".section-title, .fade-in").forEach(el => {
    observer.observe(el);
});

// Language Switcher Toggle
const langBtn = document.getElementById("langBtn");
const langOptions = document.getElementById("langOptions");

if (langBtn) {
    langBtn.addEventListener("click", () => {
        langOptions.classList.toggle("active");
    });

    document.addEventListener("click", (e) => {
        if (!langBtn.contains(e.target) && !langOptions.contains(e.target)) {
            langOptions.classList.remove("active");
        }
    });
}

// Translations Dictionary
const translations = {
    bg: {
        nav_home: "Начало",
        nav_history: "История",
        nav_treasures: "Съкровища",
        nav_dates: "Важни дати",
        hero_title: "Bulgaria",
        history_title: "История",
        history_desc: "България има богата и древна история, обхващаща хилядолетия. От древните траки до съвременната държава, всяка епоха е оставила своя отпечатък.",
        treasures_title: "Съкровища",
        treasures_desc: "България е дом на някои от най-впечатляващите антични съкровища в света, разкриващи величието на древните цивилизации.",
        btn_learn_more: "Научи повече",
        btn_discover_more: "Открий повече",
        back_to_home: "Назад към началото",
        history_page_title: "История на България",
        dates_page_title: "Важни дати",
        burgas_hero_tagline: "Градът на морето, птиците и фестивалите",
        burgas_welcome_title: "Добре дошли в Бургас",
        burgas_welcome_desc: "Бургас е четвъртият по големина град в България, разположен на красивия бряг на Черно море. Известен със своята Морска градина, фестивала на пясъчните фигури и гостоприемния си дух, градът е перфектната дестинация за почивка и културни преживявания.",
        burgas_card_garden_title: "Морска градина",
        burgas_card_garden_desc: "Един от най-големите и красиви паркове в България, простиращ се покрай морския бряг.",
        burgas_card_sand_title: "Пясъчни фигури",
        burgas_card_sand_desc: "Ежегоден фестивал, събиращ творци от цял свят, които създават шедьоври от пясък.",
        burgas_card_port_title: "Пристанище Бургас",
        burgas_card_port_desc: "Модерна зона за отдих с красив фар, ресторанти и места за разходка.",
        back_to_burgas: "Назад към Бургас",
        burgas_history_page_title: "История на Бургас",
        burgas_history_p1: "Историята на Бургас датира от хилядолетия, като първите селища в района са от времето на траките. Древните лечебни извори на Акве Калиде са привличали посетители още от античността, включително римски императори и византийски владетели.",
        burgas_history_p2: "През средновековието районът е бил важен стратегически пункт, но истинският разцвет на града започва в края на 19-ти и началото на 20-ти век. Изграждането на пристанището превръща Бургас в основен търговски и икономически център на южното Черноморие.",
        burgas_history_p3: "Днес Бургас е модерен европейски град, който пази своето културно наследство, докато смело гледа към бъдещето като фестивален и туристически център от световна величина.",
        burgas_garden_details_title: "Морската градина – Сърцето на града",
        burgas_garden_details_p1: "Морската градина е белият дроб на Бургас. Тя е един от най-големите и красиви паркове в България, простиращ се на площ от стотици декари покрай морския бряг.",
        burgas_garden_details_p2: "В парка се намират множество паметници на видни личности, екзотични растения, Летният театър и културният център 'Морско казино'. Това е идеалното място за разходка, спорт и отдих.",
        burgas_sand_details_title: "Магията на Пясъчните фигури",
        burgas_sand_details_p1: "Всяко лято Бургас се превръща в сцена на едно от най-впечатляващите събития в България – Фестивала на пясъчните фигури.",
        burgas_sand_details_p2: "Майстори от цял свят използват хиляди тонове специален пясък, за да извайват герои от приказки, филми и историята. Изложбата е разположена в парк 'Езеро' и е отворена през целия летен сезон.",
        burgas_port_details_title: "Пристанище Бургас – Врата към света",
        burgas_port_details_p1: "Пристанището на Бургас е не само икономически възел, но и една от най-модерните зони за отдих в България.",
        burgas_port_details_p2: "Зоната за свободен достъп включва обновената 'Магазия 1', Морската гара и емблематичния Фар. Тук можете да се насладите на прекрасна морска панорама, ресторанти и културни събития.",
        treasures_page_title: "Съкровищата на България",
        treasures_page_desc: "Българските земи са съхранили невероятни златни и сребърни съкровища, които днес са сред най-ценните експонати в световните музеи.",
        treasure_pan_title: "Панагюрското златно съкровище",
        treasure_pan_short: "Едно от най-известните тракийски съкровища в света. Състои се от 9 съда от чисто злато (над 6 кг).",
        treasure_pan_p1: "Панагюрското златно съкровище е най-известното тракийски съкровище в света. То е открито на 8 декември 1949 г. от трима братя – Павел, Петко и Михаил Дейкови, по време на изкопни работи в околностите на град Панагюрище.",
        treasure_pan_p2: "Съкровището се състои от 9 съда, изработени от чисто злато (23-каратово) с общо тегло 6.164 кг. Комплектът включва една фиала и осем ритона, украсени с изключително сложни и детайлни сцени от античната митология.",
        treasure_pan_desc_title: "Описание на съдовете:",
        treasure_pan_p3: "Централният съд е амфора-ритон, чиито дръжки са оформени като борещи се кентаври. Други ритони изобразяват глави на животни (овен, елен) и на богини (Атина, Хера, Афродита).",
        treasure_pan_p4: "Предполага се, че съкровището е било собственост на владетел на одрисите от края на IV или началото на III в. пр.н.е. То е използвано за ритуални цели и пиршества, демонстрирайки богатството и високата култура на траките.",
        treasure_var_title: "Варненското златно съкровище",
        treasure_var_short: "Това е най-старото обработено злато в света, датиращо от преди повече от 6000 години.",
        treasure_var_p1: "Варненското златно съкровище е най-старото технологично обработено злато в света. То е открито през 1972 г. по време на археологически разкопки във Варненския халколитен некропол.",
        treasure_var_p2: "Находката датира от края на V хилядолетие пр.н.е. (преди повече от 6000 години). Съкровището включва над 3000 златни предмета с общо тегло около 6 кг, което е изключително количество за онази епоха.",
        treasure_var_desc_title: "Историческо значение:",
        treasure_var_p3: "Варненското съкровище доказва съществуването на високоразвита цивилизация край черноморския бряг, наречена 'Култура Варна'. Тази цивилизация е познавала сложни металургични процеси и е имала ясно изразена социална йерархия.",
        treasure_var_p4: "Най-известният гроб (№43) съдържа останките на мъж, вероятно владетел или жрец, погребан с над 1.5 кг златни предмети, включително златен жезъл – символ на властта.",
        treasure_rog_title: "Рогозенското съкровище",
        treasure_rog_short: "Най-голямото по обем тракийско съкровище, състоящо се от 165 сребърни съда.",
        treasure_rog_p1: "Рогозенското съкровище е най-голямото по обем тракийско съкровище, откривано някога. То е намерено случайно през 1985-1986 г. в село Рогозен, Врачанско.",
        treasure_rog_p2: "Съкровището се състои от 165 сребърни съда, някои от които са позлатени. Общото им тегло е близо 20 кг. Колекцията включва фиали, кани и една скифос.",
        treasure_rog_p3: "Съдовете са украсени с богати релефни сцени, изобразяващи тракийски божества, ловни сцени и митологични същества. Много от предметите носят надписи с имената на тракийски владетели и майстори.",
        treasure_val_title: "Вълчитрънското златно съкровище",
        treasure_val_short: "Съставено от 13 златни предмета с общо тегло 12.5 кг. Едно от най-масивните в Европа.",
        treasure_val_p1: "Вълчитрънското златно съкровище е едно от най-загадъчните и масивни съкровища в света. То е открито през 1924 г. в село Вълчитрън, Плевенско.",
        treasure_val_p2: "Съкровището се състои от 13 златни предмета с общо тегло 12.5 кг чисто злато. Най-впечатляващ е големият кантарос (съд за вино) с две дръжки, тежащ над 4 кг.",
        treasure_val_p3: "Предметите датират от края на бронзовата епоха (XIV-XIII в. пр.н.е.). Те са били използвани за религиозни ритуали от тракийските жреци-царе.",
        back_to_treasures: "Назад към съкровищата",
        btn_read_more: "Прочети повече",
        pgmee_hero_subtitle: "Знание, професионализъм, бъдеще",
        pgmee_about_title: "За училището",
        pgmee_about_desc: "Професионална гимназия по механоелектротехника и електроника (ПГМЕЕ) е едно от най-престижните учебни заведения в град Бургас. С дългогодишна история и иновативни методи на обучение, ние подготвяме следващото поколение инженери и технически специалисти.",
        pgmee_stat1_val: "100+",
        pgmee_stat1_label: "Години опит",
        pgmee_stat2_val: "900+",
        pgmee_stat2_label: "Ученици",
        pgmee_specialties_title: "Специалности",
        pgmee_spec1_title: "Автотранспорт",
        pgmee_spec1_desc: "Съвременна диагностика и ремонт на автомобили.",
        pgmee_spec2_title: "Електроника",
        pgmee_spec2_desc: "Проектиране и поддръжка на електронни системи.",
        pgmee_spec3_title: "Мехатроника",
        pgmee_spec3_desc: "Бъдещето на автоматизацията и роботиката.",
        pgmee_success_title: "Нашите успехи",
        pgmee_success1_title: "Национални състезания",
        pgmee_success1_desc: "Множество призови места и златни медали в състезания по електроника и механика.",
        pgmee_success2_title: "Партньорства",
        pgmee_success2_desc: "Успешно сътрудничество с водещи компании в индустрията за дуално обучение.",
        pgmee_success3_title: "Иновации",
        pgmee_success3_desc: "Собствени патенти и иновативни разработки на наши ученици в сферата на роботиката."
    },
    en: {
        nav_home: "Home",
        nav_history: "History",
        nav_treasures: "Treasures",
        nav_dates: "Important Dates",
        hero_title: "Bulgaria",
        history_title: "History",
        history_desc: "Bulgaria has a rich and ancient history spanning millennia. From the ancient Thracians to the modern state, each era has left its mark.",
        treasures_title: "Treasures",
        treasures_desc: "Bulgaria is home to some of the most impressive ancient treasures in the world, revealing the greatness of ancient civilizations.",
        btn_learn_more: "Learn More",
        btn_discover_more: "Discover More",
        back_to_home: "Back to Home",
        history_page_title: "History of Bulgaria",
        dates_page_title: "Important Dates",
        burgas_hero_tagline: "The city of the sea, birds and festivals",
        burgas_welcome_title: "Welcome to Burgas",
        burgas_welcome_desc: "Burgas is the fourth largest city in Bulgaria, located on the beautiful coast of the Black Sea. Known for its Sea Garden, the sand figures festival and its hospitable spirit, the city is the perfect destination for relaxation and cultural experiences.",
        burgas_card_garden_title: "Sea Garden",
        burgas_card_garden_desc: "One of the largest and most beautiful parks in Bulgaria, stretching along the seashore.",
        burgas_card_sand_title: "Sand Figures",
        burgas_card_sand_desc: "An annual festival bringing together artists from all over the world who create masterpieces from sand.",
        burgas_card_port_title: "Port of Burgas",
        burgas_card_port_desc: "A modern recreation area with a beautiful lighthouse, restaurants and places for walking.",
        back_to_burgas: "Back to Burgas",
        burgas_history_page_title: "History of Burgas",
        burgas_history_p1: "The history of Burgas dates back millennia, with the first settlements in the area from the time of the Thracians. The ancient healing springs of Aquae Calidae have attracted visitors since antiquity, including Roman emperors and Byzantine rulers.",
        burgas_history_p2: "During the Middle Ages, the area was an important strategic point, but the city's true prosperity began in the late 19th and early 20th centuries. The construction of the port turned Burgas into a major commercial and economic center of the southern Black Sea coast.",
        burgas_history_p3: "Today, Burgas is a modern European city that preserves its cultural heritage while boldly looking to the future as a world-class festival and tourist center.",
        burgas_garden_details_title: "The Sea Garden – The Heart of the City",
        burgas_garden_details_p1: "The Sea Garden is the lungs of Burgas. It is one of the largest and most beautiful parks in Bulgaria, stretching over hundreds of acres along the seashore.",
        burgas_garden_details_p2: "The park is home to numerous monuments of prominent figures, exotic plants, the Summer Theater, and the 'Sea Casino' cultural center. It is the perfect place for walking, sports, and relaxation.",
        burgas_sand_details_title: "The Magic of Sand Figures",
        burgas_sand_details_p1: "Every summer, Burgas becomes the stage for one of the most impressive events in Bulgaria – the Sand Figures Festival.",
        burgas_sand_details_p2: "Masters from all over the world use thousands of tons of special sand to carve characters from fairy tales, movies, and history. The exhibition is located in 'Ezero' Park and is open throughout the summer season.",
        burgas_port_details_title: "Port of Burgas – Gateway to the World",
        burgas_port_details_p1: "The Port of Burgas is not only an economic hub but also one of the most modern recreation areas in Bulgaria.",
        burgas_port_details_p2: "The public access zone includes the renovated 'Magazia 1', the Marine Station, and the iconic Lighthouse. Here you can enjoy a beautiful sea panorama, restaurants, and cultural events.",
        treasures_page_title: "Treasures of Bulgaria",
        treasures_page_desc: "Bulgarian lands have preserved incredible gold and silver treasures, which today are among the most valuable exhibits in world museums.",
        treasure_pan_title: "Panagyurishte Gold Treasure",
        treasure_pan_short: "One of the most famous Thracian treasures in the world. It consists of 9 vessels of pure gold (over 6 kg).",
        treasure_pan_p1: "The Panagyurishte Gold Treasure is the most famous Thracian treasure in the world. It was discovered on December 8, 1949, by three brothers – Pavel, Petko, and Mihail Deykovi, during excavation work near the town of Panagyurishte.",
        treasure_pan_p2: "The treasure consists of 9 vessels made of pure gold (23-carat) with a total weight of 6.164 kg. The set includes one phiale and eight rhytons, decorated with extremely complex and detailed scenes from ancient mythology.",
        treasure_pan_desc_title: "Description of the vessels:",
        treasure_pan_p3: "The central vessel is an amphora-rhyton, whose handles are shaped like struggling centaurs. Other rhytons depict the heads of animals (ram, deer) and goddesses (Athena, Hera, Aphrodite).",
        treasure_pan_p4: "It is assumed that the treasure was the property of an Odrysian ruler from the late 4th or early 3rd century BC. It was used for ritual purposes and feasts, demonstrating the wealth and high culture of the Thracians.",
        treasure_var_title: "Varna Gold Treasure",
        treasure_var_short: "This is the oldest processed gold in the world, dating back more than 6,000 years.",
        treasure_var_p1: "The Varna Gold Treasure is the oldest technologically processed gold in the world. It was discovered in 1972 during archaeological excavations at the Varna Eneolithic Necropolis.",
        treasure_var_p2: "The find dates back to the end of the 5th millennium BC (more than 6,000 years ago). The treasure includes over 3,000 gold items with a total weight of about 6 kg, which is an exceptional amount for that era.",
        treasure_var_desc_title: "Historical Significance:",
        treasure_var_p3: "The Varna Treasure proves the existence of a highly developed civilization on the Black Sea coast, called 'Varna Culture'. This civilization knew complex metallurgical processes and had a clearly defined social hierarchy.",
        treasure_var_p4: "The most famous grave (No. 43) contains the remains of a man, probably a ruler or priest, buried with over 1.5 kg of gold items, including a gold scepter – a symbol of power.",
        treasure_rog_title: "Rogozen Treasure",
        treasure_rog_short: "The largest Thracian treasure in volume, consisting of 165 silver vessels.",
        treasure_rog_p1: "The Rogozen Treasure is the largest Thracian treasure in volume ever found. It was discovered accidentally in 1985-1986 in the village of Rogozen, Vratsa region.",
        treasure_rog_p2: "The treasure consists of 165 silver vessels, some of which are gilded. Their total weight is nearly 20 kg. The collection includes phiales, jugs, and one skyphos.",
        treasure_rog_p3: "The vessels are decorated with rich relief scenes depicting Thracian deities, hunting scenes, and mythological creatures. Many items bear inscriptions with the names of Thracian rulers and craftsmen.",
        treasure_val_title: "Valchitrun Gold Treasure",
        treasure_val_short: "Composed of 13 gold items with a total weight of 12.5 kg. One of the most massive in Europe.",
        treasure_val_p1: "The Valchitrun Gold Treasure is one of the most mysterious and massive treasures in the world. It was discovered in 1924 in the village of Valchitrun, Pleven region.",
        treasure_val_p2: "The treasure consists of 13 gold items with a total weight of 12.5 kg of pure gold. The most impressive is the large kantharos (wine vessel) with two handles, weighing over 4 kg.",
        treasure_val_p3: "The items date back to the late Bronze Age (14th-13th century BC). They were used for religious rituals by Thracian priest-kings.",
        back_to_treasures: "Back to treasures",
        btn_read_more: "Read more",
        pgmee_hero_subtitle: "Knowledge, professionalism, future",
        pgmee_about_title: "About the school",
        pgmee_about_desc: "Vocational High School of Mechanical and Electrical Engineering and Electronics (PGMEE) is one of the most prestigious educational institutions in the city of Burgas. With a long history and innovative teaching methods, we prepare the next generation of engineers and technical specialists.",
        pgmee_stat1_val: "100+",
        pgmee_stat1_label: "Years of experience",
        pgmee_stat2_val: "900+",
        pgmee_stat2_label: "Students",
        pgmee_specialties_title: "Specialties",
        pgmee_spec1_title: "Automotive Transport",
        pgmee_spec1_desc: "Modern diagnosis and repair of cars.",
        pgmee_spec2_title: "Electronics",
        pgmee_spec2_desc: "Design and maintenance of electronic systems.",
        pgmee_spec3_title: "Mechatronics",
        pgmee_spec3_desc: "The future of automation and robotics.",
        pgmee_success_title: "Our Successes",
        pgmee_success1_title: "National Competitions",
        pgmee_success1_desc: "Numerous top places and gold medals in electronics and mechanics competitions.",
        pgmee_success2_title: "Partnerships",
        pgmee_success2_desc: "Successful cooperation with leading industry companies for dual education.",
        pgmee_success3_title: "Innovations",
        pgmee_success3_desc: "Our students' own patents and innovative developments in the field of robotics."
    },
    de: {
        nav_home: "Startseite",
        nav_history: "Geschichte",
        nav_treasures: "Schätze",
        nav_dates: "Wichtige Daten",
        hero_title: "Bulgarien",
        history_title: "Geschichte",
        history_desc: "Bulgarien hat eine reiche und alte Geschichte, die Jahrtausende umspannt. Von den alten Thrakern bis zum modernen Staat hat jede Ära ihre Spuren hinterlassen.",
        treasures_title: "Schätze",
        treasures_desc: "Bulgarien beherbergt einige der beeindruckendsten antiken Schätze der Welt, die die Größe alter Zivilisationen offenbaren.",
        btn_learn_more: "Mehr erfahren",
        btn_discover_more: "Mehr entdecken",
        back_to_home: "Zurück zur Startseite",
        history_page_title: "Geschichte Bulgariens",
        dates_page_title: "Wichtige Daten",
        burgas_hero_tagline: "Die Stadt des Meeres, der Vögel und der Festivals",
        burgas_welcome_title: "Willkommen in Burgas",
        burgas_welcome_desc: "Burgas ist die viertgrößte Stadt Bulgariens und liegt an der wunderschönen Küste des Schwarzen Meeres. Bekannt für seinen Meeresgarten, das Sandfigurenfestival und seinen gastfreundlichen Geist, ist die Stadt das perfekte Ziel für Entspannung und kulturelle Erlebnisse.",
        burgas_card_garden_title: "Meeresgarten",
        burgas_card_garden_desc: "Einer der größten und schönsten Parks Bulgariens, der sich entlang der Meeresküste erstreckt.",
        burgas_card_sand_title: "Sandfiguren",
        burgas_card_sand_desc: "Ein jährliches Festival, bei dem Künstler aus der ganzen Welt Meisterwerke aus Sand erschaffen.",
        burgas_card_port_title: "Hafen von Burgas",
        burgas_card_port_desc: "Ein modernes Erholungsgebiet mit einem schönen Leuchtturm, Restaurants und Orten zum Wandern.",
        back_to_burgas: "Zurück nach Burgas",
        burgas_history_page_title: "Geschichte von Burgas",
        burgas_history_p1: "Die Geschichte von Burgas reicht Jahrtausende zurück, wobei die ersten Siedlungen in der Gegend aus der Zeit der Thraker stammen. Die alten Heilquellen von Aquae Calidae ziehen seit der Antike Besucher an, darunter römische Kaiser und byzantinische Herrscher.",
        burgas_history_p2: "Im Mittelalter war die Gegend ein wichtiger strategischer Punkt, но истинският разцвет на града започва в края на 19-ти и началото на 20-ти век. Der Bau des Hafens machte Burgas zu einem bedeutenden Handels- und Wirtschaftszentrum an der südlichen Schwarzmeerküste.",
        burgas_history_p3: "Heute ist Burgas eine moderne europäische Stadt, die ihr kulturelles Erbe bewahrt und gleichzeitig mutig in die Zukunft als Festival- und Tourismuszentrum von Weltrang blickt.",
        burgas_garden_details_title: "Der Meeresgarten – Das Herz der Stadt",
        burgas_garden_details_p1: "Der Meeresgarten ist die Lunge von Burgas. Er ist einer der größten und schönsten Parks Bulgariens und erstreckt sich über hunderte von Hektar entlang der Meeresküste.",
        burgas_garden_details_p2: "Der Park beherbergt zahlreiche Denkmäler prominenter Persönlichkeiten, exotische Pflanzen, das Sommertheater und das Kulturzentrum 'Sea Casino'. Es ist der perfekte Ort zum Wandern, Sporttreiben und Entspannen.",
        burgas_sand_details_title: "Die Magie der Sandfiguren",
        burgas_sand_details_p1: "Jeden Sommer wird Burgas zur Bühne für eines der beeindruckendsten Ereignisse in Bulgarien – das Sandfiguren-Festival.",
        burgas_sand_details_p2: "Meister aus der ganzen Welt verwenden tausende Tonnen Spezialsand, um Figuren aus Märchen, Filmen und der Geschichte zu schnitzen. Die Ausstellung befindet sich im 'Ezero'-Park und ist während der gesamten Sommersaison geöffnet.",
        burgas_port_details_title: "Hafen von Burgas – Tor zur Welt",
        burgas_port_details_p1: "Der Hafen von Burgas ist nicht nur ein Wirtschaftsknotenpunkt, sondern auch eines der modernsten Erholungsgebiete Bulgariens.",
        burgas_port_details_p2: "Die frei zugängliche Zone umfasst das renovierte 'Magazia 1', den Marinestützpunkt und den legendären Leuchtturm. Hier können Sie ein wunderschönes Meerespanorama, Restaurants und kulturelle Veranstaltungen genießen.",
        treasures_page_title: "Schätze Bulgariens",
        treasures_page_desc: "Die bulgarischen Länder haben unglaubliche Gold- und Silberschätze bewahrt, die heute zu den wertvollsten Exponaten in Weltmuseen gehören.",
        treasure_pan_title: "Panagyurishte Gold Treasure",
        treasure_pan_short: "Einer der berühmtesten thrakischen Schätze der Welt. Er besteht aus 9 Gefäßen aus reinem Gold (über 6 kg).",
        treasure_pan_p1: "Der Goldschatz von Panagjurischte ist der berühmteste thrakische Schatz der Welt. Er wurde am 8. Dezember 1949 von drei Brüdern – Pavel, Petko und Mihail Deykovi – bei Ausgrabungsarbeiten in der Nähe der Stadt Panagjurischte entdeckt.",
        treasure_pan_p2: "Der Schatz besteht aus 9 Gefäßen aus reinem Gold (23 Karat) mit einem Gesamtgewicht von 6,164 kg. Das Set umfasst eine Phiale und acht Rhyta, die mit äußerst komplexen und detaillierten Szenen aus der antiken Mythologie verziert sind.",
        treasure_pan_desc_title: "Beschreibung der Gefäße:",
        treasure_pan_p3: "Das zentrale Gefäß ist ein Amphoren-Rhyton, dessen Henkel wie kämpfende Kentauren geformt sind. Andere Rhyta zeigen Tierköpfe (Widder, Hirsch) und Göttinnen (Athene, Hera, Aphrodite).",
        treasure_pan_p4: "Es wird angenommen, dass der Schatz Eigentum eines odrysischen Herrschers aus dem späten 4. oder frühen 3. Jahrhundert v. Chr. war. Er wurde für rituelle Zwecke und Feste verwendet und demonstriert den Reichtum und die hohe Kultur der Thraker.",
        treasure_var_title: "Varna Gold Treasure",
        treasure_var_short: "Dies ist das älteste verarbeitete Gold der Welt, das mehr als 6.000 Jahre alt ist.",
        treasure_var_p1: "Der Goldschatz von Warna ist das älteste technologisch verarbeitete Gold der Welt. Er wurde 1972 bei archäologischen Ausgrabungen in der kupferzeitlichen Nekropole von Warna entdeckt.",
        treasure_var_p2: "Der Fund stammt aus dem Ende des 5. Jahrtausends v. Chr. (vor mehr als 6.000 Jahren). Der Schatz umfasst über 3.000 Goldgegenstände mit einem Gesamtgewicht von etwa 6 kg, was für diese Zeit eine außergewöhnliche Menge ist.",
        treasure_var_desc_title: "Historische Bedeutung:",
        treasure_var_p3: "Der Schatz von Warna beweist die Existenz einer hochentwickelten Zivilisation an der Schwarzmeerküste, die 'Warna-Kultur' genannt wird. Diese Zivilisation kannte komplexe metallurgische Prozesse und hatte eine klar definierte soziale Hierarchie.",
        treasure_var_p4: "Das berühmteste Grab (Nr. 43) enthält die Überreste eines Mannes, wahrscheinlich ein Herrscher oder Priester, der mit über 1,5 kg Goldgegenständen begraben wurde, darunter ein goldenes Zepter – ein Symbol der Macht.",
        treasure_rog_title: "Rogozen Treasure",
        treasure_rog_short: "Der volumenmäßig größte thrakische Schatz, bestehend aus 165 Silbergefäßen.",
        treasure_rog_p1: "Der Schatz von Rogozen ist der volumenmäßig größte thrakische Schatz, der je gefunden wurde. Er wurde 1985-1986 zufällig im Dorf Rogozen in der Region Wraza entdeckt.",
        treasure_rog_p2: "Der Schatz besteht aus 165 Silbergefäßen, von denen einige vergoldet sind. Ihr Gesamtgewicht beträgt fast 20 kg. Die Sammlung umfasst Phialen, Krüge und einen Skyphos.",
        treasure_rog_p3: "Die Gefäße sind mit reichen Reliefszenen verziert, die thrakische Gottheiten, Jagdszenen und Fabelwesen darstellen. Viele Gegenstände tragen Inschriften mit den Namen thrakischer Herrscher und Handwerker.",
        treasure_val_title: "Valchitrun Gold Treasure",
        treasure_val_short: "Bestehend aus 13 Goldgegenständen mit einem Gesamtgewicht von 12,5 kg. Einer der massivsten in Europa.",
        treasure_val_p1: "Der Goldschatz von Waltschedram ist einer der mysteriösesten und massivsten Schätze der Welt. Er wurde 1924 im Dorf Waltschedram in der Region Plewen entdeckt.",
        treasure_val_p2: "Der Schatz besteht aus 13 Goldgegenständen mit einem Gesamtgewicht von 12,5 kg reinem Gold. Am beeindruckendsten ist der große Kantharos (Weingefäß) mit zwei Henkeln, der über 4 kg wiegt.",
        treasure_val_p3: "Die Gegenstände stammen aus der späten Bronzezeit (14.-13. Jahrhundert v. Chr.). Sie wurden von thrakischen Priesterkönigen für religiöse Rituale verwendet.",
        back_to_treasures: "Zurück zu den Schätzen",
        btn_read_more: "Weiterlesen",
        pgmee_hero_subtitle: "Wissen, Professionalität, Zukunft",
        pgmee_about_title: "Über die Schule",
        pgmee_about_desc: "Die Berufsoberschule für Maschinenbau, Elektrotechnik und Elektronik (PGMEE) ist eine der renommiertesten Bildungseinrichtungen in der Stadt Burgas. Mit einer langen Geschichte und innovativen Lehrmethoden bereiten wir die nächste Generation von Ingenieuren und technischen Spezialisten vor.",
        pgmee_stat1_val: "100+",
        pgmee_stat1_label: "Jahre Erfahrung",
        pgmee_stat2_val: "900+",
        pgmee_stat2_label: "Schüler",
        pgmee_specialties_title: "Fachrichtungen",
        pgmee_spec1_title: "Kraftfahrzeugtechnik",
        pgmee_spec1_desc: "Moderne Diagnose und Reparatur von Autos.",
        pgmee_spec2_title: "Elektronik",
        pgmee_spec2_desc: "Design und Wartung elektronischer Systeme.",
        pgmee_spec3_title: "Mechatronik",
        pgmee_spec3_desc: "Die Zukunft der Automatisierung und Robotik.",
        pgmee_success_title: "Unsere Erfolge",
        pgmee_success1_title: "Nationale Wettbewerbe",
        pgmee_success1_desc: "Zahlreiche Spitzenplätze und Goldmedaillen in Elektronik- und Mechanikwettbewerben.",
        pgmee_success2_title: "Partnerschaften",
        pgmee_success2_desc: "Erfolgreiche Zusammenarbeit mit führenden Industrieunternehmen für die duale Ausbildung.",
        pgmee_success3_title: "Innovationen",
        pgmee_success3_desc: "Eigene Patente und innovative Entwicklungen unserer Schüler im Bereich Robotik."
    },
    el: {
        nav_home: "Αρχική",
        nav_history: "Ιστορία",
        nav_treasures: "Θησαυροί",
        nav_dates: "Σημαντικές Ημερομηνίες",
        hero_title: "Βουλγαρία",
        history_title: "Ιστορία",
        history_desc: "Η Βουλγαρία έχει μια πλούσια και αρχαία ιστορία που εκτείνεται σε χιλιετίες. Από τους αρχαίους Θράκες μέχρι το σύγχρονο κράτος, κάθε εποχή έχει αφήσει το στίγμα της.",
        treasures_title: "Θησαυροί",
        treasures_desc: "Η Βουλγαρία φιλοξενεί μερικούς από τους πιο εντυπωσιακούς αρχαίους θησαυρούς στον κόσμο, αποκαλύπτοντας το μεγαλείο των αρχαίων πολιτισμών.",
        btn_learn_more: "Μάθετε περισσότερα",
        btn_discover_more: "Ανακαλύψτε περισσότερα",
        back_to_home: "Επιστροφή στην αρχική",
        history_page_title: "Ιστορία της Βουλγαρίας",
        dates_page_title: "Σημαντικές Ημερομηνίες",
        burgas_hero_tagline: "Η πόλη της θάλασσας, των πουλιών και των φεστιβάλ",
        burgas_welcome_title: "Καλώς ήρθατε στον Πύργο",
        burgas_welcome_desc: "Ο Πύργος (Μπουργκάς) είναι η τέταρτη μεγαλύτερη πόλη της Βουλγαρίας, που βρίσκεται στην πανέμορφη ακτή της Μαύρης Θάλασσας. Γνωστή για τον Θαλάσσιο Κήπο της, το φεστιβάλ γλυπτών από άμμο και το φιλόξενο πνεύμα της, η πόλη είναι ο τέλειος προορισμός για χαλάρωση και πολιτιστικές εμπειρίες.",
        burgas_card_garden_title: "Θαλάσσιος Κήπος",
        burgas_card_garden_desc: "Ένα από τα μεγαλύτερα και ομορφότερα πάρκα της Βουλγαρίας, που εκτείνεται κατά μήκος της παραλίας.",
        burgas_card_sand_title: "Γλυπτά από Άμμο",
        burgas_card_sand_desc: "Ένα ετήσιο φεστιβάλ που συγκεντρώνει καλλιτέχνες από όλο τον κόσμο που δημιουργούν αριστουργήματα από άμμο.",
        burgas_card_port_title: "Λιμάνι του Μπουργκάς",
        burgas_card_port_desc: "Μια σύγχρονη περιοχή αναψυχής με έναν όμορφο φάρο, εστιατόρια και μέρη για περίπατο.",
        back_to_burgas: "Πίσω στο Μπουργκάς",
        burgas_history_page_title: "Ιστορία του Μπουργκάς",
        burgas_history_p1: "Η ιστορία του Μπουργκάς χρονολογείται χιλιετίες πίσω, με τους πρώτους οικισμούς στην περιοχή από την εποχή των Θρακών. Οι αρχαίες ιαματικές πηγές των Aquae Calidae έχουν προσελκύσει επισκέπτες από την αρχαιότητα, συμπεριλαμβανομένων Ρωμαίων αυτοκρατόρων και Βυζαντινών ηγεμόνων.",
        burgas_history_p2: "Κατά τη διάρκεια του Μεσαίωνα, η περιοχή ήταν σημαντικό στρατηγικό σημείο, αλλά η πραγματική άνθηση της πόλης ξεκίνησε στα τέλη του 19ου και στις αρχές του 20ού αιώνα. Η κατασκευή του λιμανιού μετέτρεψε το Μπουργκάς σε σημαντικό εμπορικό και οικονομικό κέντρο των νότιων ακτών της Μαύρης Θάλασσας.",
        burgas_history_p3: "Σήμερα, το Μπουργκάς είναι μια σύγχρονη ευρωπαϊκή πόλη που διατηρεί την πολιτιστική της κληρονομιά, ενώ κοιτάζει τολμηρά προς το μέλλον ως φεστιβάλ και τουριστικό κέντρο παγκόσμιας κλάσης.",
        burgas_garden_details_title: "Ο Θαλάσσιος Κήπος – Η Καρδιά της Πόλης",
        burgas_garden_details_p1: "Ο Θαλάσσιος Κήπος είναι ο πνεύμονας του Μπουργκάς. Είναι ένα από τα μεγαλύτερα και ομορφότερα πάρκα της Βουλγαρίας, που εκτείνεται σε εκατοντάδες στρέμματα κατά μήκος της παραλίας.",
        burgas_garden_details_p2: "Το πάρκο φιλοξενεί πολυάριθμα μνημεία εξεχουσών προσωπικοτήτων, εξωτικά φυτά, το Θερινό Θέατρο και το πολιτιστικό κέντρο 'Sea Casino'. Είναι το ιδανικό μέρος για περπάτημα, σπορ και χαλάρωση.",
        burgas_sand_details_title: "Η Μαγεία των Γλυπτών από Άμμο",
        burgas_sand_details_p1: "Κάθε καλοκαίρι, το Μπουργκάς γίνεται η σκηνή για ένα από τα πιο εντυπωσιακά γεγονότα στη Βουλγαρία – το Φεστιβάλ Γλυπτών από Άμμο.",
        burgas_sand_details_p2: "Καλλιτέχνες από όλο τον κόσμο χρησιμοποιούν χιλιάδες τόνους ειδικής άμμου για να σμιλέψουν χαρακτήρες από παραμύθια, ταινίες και την ιστορία. Η έκθεση βρίσκεται στο πάρκο 'Ezero' και είναι ανοιχτή καθ' όλη τη διάρκεια της καλοκαιρινής περιόδου.",
        burgas_port_details_title: "Λιμάνι του Μπουργκάς – Πύλη προς τον Κόσμο",
        burgas_port_details_p1: "Το Λιμάνι του Μπουργκάς δεν είναι μόνο ένας οικονομικός κόμβος, αλλά και μία από τις πιο σύγχρονες περιοχές αναψυχής στη Βουλγαρία.",
        burgas_port_details_p2: "Η ζώνη δημόσιας πρόσβασης περιλαμβάνει την ανακαινισμένη 'Magazia 1', τον Ναυτικό Σταθμό και τον εμβληματικό Φάρο. Εδώ μπορείτε να απολαύσετε ένα όμορφο θαλάσσιο πανόραμα, εστιατόρια και πολιτιστικές εκδηλώσεις.",
        treasures_page_title: "Θησαυροί της Βουλγαρίας",
        treasures_page_desc: "Τα βουλγαρικά εδάφη έχουν διατηρήσει απίστευτους θησαυρούς από χρυσό και ασήμι, οι οποίοι σήμερα συγκαταλέγονται στα πιο πολύτιμα εκθέματα στα παγκόσμια μουσεία.",
        treasure_pan_title: "Panagyurishte Gold Treasure",
        treasure_pan_short: "Ένας από τους πιο διάσημους θρακικούς θησαυρούς στον κόσμο. Αποτελείται από 9 σκεύη από καθαρό χρυσό (πάνω από 6 κιλά).",
        treasure_pan_p1: "Ο χρυσός θησαυρός του Παναγκιουρίστε είναι ο πιο διάσημος θρακικός θησαυρός στον κόσμο. Ανακαλύφθηκε στις 8 Δεκεμβρίου 1949 από τρία αδέρφια – τον Πάβελ, τον Πέτκο και τον Μιχαήλ Ντέικοφ, κατά τη διάρκεια εργασιών εκσκαφής κοντά στην πόλη Παναγκιουρίστε.",
        treasure_pan_p2: "Ο θησαυρός αποτελείται από 9 σκεύη από καθαρό χρυσό (23 καρατίων) με συνολικό βάρος 6,164 κιλά. Το σετ περιλαμβάνει μία φιάλη και οκτώ ρυτά, διακοσμημένα με εξαιρετικά πολύπλοκες και λεπτομερείς σκηνές από την αρχαία μυθολογία.",
        treasure_pan_desc_title: "Περιγραφή των σκευών:",
        treasure_pan_p3: "Το κεντρικό σκεύος είναι ένας αμφορέας-ρυτό, του οποίου οι λαβές έχουν σχήμα Κενταύρων που παλεύουν. Άλλα ρυτά απεικονίζουν κεφαλές ζώων (κριού, ελαφιού) και θεών (Αθηνά, Ήρα, Αφροδίτη).",
        treasure_pan_p4: "Υποτίθεται ότι ο θησαυρός ήταν ιδιοκτησία ενός Οδρύσου ηγεμόνα από τα τέλη του 4ου ή τις αρχές του 3ου αιώνα π.Χ. Χρησιμοποιούνταν για τελετουργικούς σκοπούς και γιορτές, αποδεικνύοντας τον πλούτο και την υψηλή κουλτούρα των Θρακών.",
        treasure_var_title: "Varna Gold Treasure",
        treasure_var_short: "Αυτός είναι ο παλαιότερος επεξεργασμένος χρυσός στον κόσμο, με ηλικία πάνω από 6.000 χρόνια.",
        treasure_var_p1: "Ο χρυσός θησαυρός της Βάρνας είναι ο παλαιότερος τεχνολογικά επεξεργασμένος χρυσός στον κόσμο. Ανακαλύφθηκε το 1972 κατά τη διάρκεια αρχαιολογικών ανασκαφών στη χαλκολιθική νεκρόπολη της Βάρνας.",
        treasure_var_p2: "Το εύρημα χρονολογείται από το τέλος της 5ης χιλιετίας π.Χ. (πριν από περισσότερα από 6.000 χρόνια). Ο θησαυρός περιλαμβάνει πάνω από 3.000 χρυσά αντικείμενα με συνολικό βάρος περίπου 6 κιλά, μια εξαιρετική ποσότητα για εκείνη την εποχή.",
        treasure_var_desc_title: "Ιστορική σημασία:",
        treasure_var_p3: "Ο θησαυρός της Βάρνας αποδεικνύει την ύπαρξη ενός ιδιαίτερα αναπτυγμένου πολιτισμού στις ακτές της Μαύρης Θάλασσας, που ονομάζεται 'Πολιτισμός της Βάρνας'. Αυτός ο πολιτισμός γνώριζε σύνθετες μεταλλουργικές διαδικασίες και είχε μια σαφώς καθορισμένη κοινωνική ιεραρχία.",
        treasure_var_p4: "Ο πιο διάσημος τάφος (αρ. 43) περιέχει τα λείψανα ενός άνδρα, πιθανώς ηγεμόνα ή ιερέα, θαμμένου με πάνω από 1,5 κιλό χρυσά αντικείμενα, συμπεριλαμβανομένου ενός χρυσού σκήπτρου – συμβόλου εξουσίας.",
        treasure_rog_title: "Rogozen Treasure",
        treasure_rog_short: "Ο μεγαλύτερος σε όγκο θρακικός θησαυρός, που αποτελείται από 165 ασημένια σκεύη.",
        treasure_rog_p1: "Ο θησαυρός του Ρογκόζεν είναι ο μεγαλύτερος σε όγκο θρακικός θησαυρός που έχει βρεθεί ποτέ. Ανακαλύφθηκε τυχαία το 1985-1986 στο χωριό Ρογκόζεν, στην περιοχή Βράτσα.",
        treasure_rog_p2: "Ο θησαυρός αποτελείται από 165 ασημένια σκεύη, ορισμένα από τα οποία είναι επιχρυσωμένα. Το συνολικό τους βάρος είναι σχεδόν 20 κιλά. Η συλλογή περιλαμβάνει φιάλες, κανάτες και ένα σκύφο.",
        treasure_rog_p3: "Τα σκεύη είναι διακοσμημένα με πλούσιες σκηνές σε ανάγλυφο, που απεικονίζουν θρακικές θεότητες, σκηνές κυνηγιού και μυθολογικά πλάσματα. Πολλά αντικείμενα φέρουν επιγραφές με τα ονόματα Θρακών ηγεμόνων και τεχνιτών.",
        treasure_val_title: "Valchitrun Gold Treasure",
        treasure_val_short: "Αποτελείται από 13 χρυσά αντικείμενα συνολικού βάρους 12,5 κιλών. Ένας από τους πιο ογκώδεις στην Ευρώπη.",
        treasure_val_p1: "Ο χρυσός θησαυρός του Βαλτσιτράν είναι ένας από τους πιο μυστηριώδεις και ογκώδεις θησαυρούς στον κόσμο. Ανακαλύφθηκε το 1924 στο χωριό Βαλτσιτράν, στην περιοχή Πλέβεν.",
        treasure_val_p2: "Ο θησαυρός αποτελείται από 13 χρυσά αντικείμενα συνολικού βάρους 12,5 κιλών καθαρού χρυσού. Το πιο εντυπωσιακό είναι το μεγάλο κάνθαρο (σκεύος κρασιού) με δύο λαβές, που ζυγίζει πάνω από 4 κιλά.",
        treasure_val_p3: "Τα αντικείμενα χρονολογούνται από την Ύστερη Εποχή του Χαλκού (14ος-13ος αιώνας π.Χ.). Χρησιμοποιούνταν για θρησκευτικές τελετές από τους Θράκες ιερείς-βασιλείς.",
        back_to_treasures: "Πίσω στους θησαυρούς",
        btn_read_more: "Διαβάστε περισσότερα",
        pgmee_hero_subtitle: "Γνώση, επαγγελματισμός, μέλλον",
        pgmee_about_title: "Σχετικά με το σχολείο",
        pgmee_about_desc: "Το Επαγγελματικό Λύκειο Μηχανολογίας και Ηλεκτρολογίας και Ηλεκτρονικής (ΠΓМЕЕ) είναι ένα από τα πιο αναγνωρισμένα εκπαιδευτικά ιδρύματα στην πόλη του Μπουργκάς. Με μακρά ιστορία και καινοτόμες μεθόδους διδασκαλίας, προετοιμάζουμε την επόμενη γενιά μηχανικών και τεχνικών ειδικών.",
        pgmee_stat1_val: "100+",
        pgmee_stat1_label: "Χρόνια εμπειρίας",
        pgmee_stat2_val: "900+",
        pgmee_stat2_label: "Μαθητές",
        pgmee_specialties_title: "Ειδικότητες",
        pgmee_spec1_title: "Αυτοκινητοβιομηχανία",
        pgmee_spec1_desc: "Σύγχρονη διάγνωση και επισκευή αυτοκινήτων.",
        pgmee_spec2_title: "Ηλεκτρονική",
        pgmee_spec2_desc: "Σχεδιασμός και συντήρηση ηλεκτρονικών συστημάτων.",
        pgmee_spec3_title: "Μηχατρονική",
        pgmee_spec3_desc: "Το μέλλον του αυτοματισμού και της ρομποτικής.",
        pgmee_success_title: "Οι Επιτυχίες μας",
        pgmee_success1_title: "Εθνικοί Διαγωνισμοί",
        pgmee_success1_desc: "Πολυάριθμες πρώτες θέσεις και χρυσά μετάλλια σε διαγωνισμούς ηλεκτρονικής και μηχανικής.",
        pgmee_success2_title: "Συνεργασίες",
        pgmee_success2_desc: "Επιτυχημένη συνεργασία με κορυφαίες εταιρείες του κλάδου για τη διπλή εκπαίδευση.",
        pgmee_success3_title: "Καινοτομίες",
        pgmee_success3_desc: "Ιδιόκτητα διπλώματα ευρεσιτεχνίας και καινοτόμες εξελίξεις των μαθητών μας στον τομέα της ρομποτικής."
    },
    fr: {
        nav_home: "Accueil",
        nav_history: "Histoire",
        nav_treasures: "Trésors",
        nav_dates: "Dates Importantes",
        hero_title: "Bulgarie",
        history_title: "Histoire",
        history_desc: "La Bulgarie possède une histoire riche et ancienne s'étendant sur des millénaires. Des anciens Thraces à l'État moderne, chaque époque a laissé sa trace.",
        treasures_title: "Trésors",
        treasures_desc: "La Bulgarie abrite certains des trésors anciens les plus impressionnants au monde, révélant la grandeur des civilisations anciennes.",
        btn_learn_more: "En savoir plus",
        btn_discover_more: "Découvrir plus",
        back_to_home: "Retour à l'accueil",
        history_page_title: "Histoire de la Bulgarie",
        dates_page_title: "Dates Importantes",
        burgas_hero_tagline: "La ville de la mer, des oiseaux et des festivals",
        burgas_welcome_title: "Bienvenue à Bourgas",
        burgas_welcome_desc: "Bourgas est la quatrième plus grande ville de Bulgarie, située sur la magnifique côte de la mer Noire. Connue pour son jardin maritime, son festival de sculptures de sable et son esprit hospitalier, la ville est la destination idéale pour la détente et les expériences culturelles.",
        burgas_card_garden_title: "Jardin Maritime",
        burgas_card_garden_desc: "L'un des parcs les plus grands et les plus beaux de Bulgarie, s'étendant le long du bord de mer.",
        burgas_card_sand_title: "Sculptures de Sable",
        burgas_card_sand_desc: "Un festival annuel réunissant des artistes du monde entier qui créent des chefs-d'œuvre à partir de sable.",
        burgas_card_port_title: "Port de Bourgas",
        burgas_card_port_desc: "Une zone de loisirs moderne avec un beau phare, des restaurants et des lieux de promenade.",
        back_to_burgas: "Retour à Bourgas",
        burgas_history_page_title: "Histoire de Bourgas",
        burgas_history_p1: "L'histoire de Bourgas remonte à des millénaires, avec les premiers peuplements de la région datant de l'époque des Thraces. Les anciennes sources thermales d'Aquae Calidae ont attiré des visiteurs depuis l'Antiquité, notamment des empereurs romains et des souverains byzantins.",
        burgas_history_p2: "Au Moyen Âge, la région était un point stratégique important, mais la véritable prospérité de la ville a commencé à la fin du XIXe et au début du XXe siècle. La construction du port a transformé Bourgas en un centre commercial et économique majeur de la côte sud de la mer Noire.",
        burgas_history_p3: "Aujourd'hui, Bourgas est une ville européenne moderne qui préserve son patrimoine culturel tout en regardant hardiment vers l'avenir en tant que centre de festivals et de tourisme de classe mondiale.",
        burgas_garden_details_title: "Le Jardin Maritime – Le Cœur de la Ville",
        burgas_garden_details_p1: "Le Jardin Maritime est le poumon de Bourgas. C'est l'un des parcs les plus grands et les plus beaux de Bulgarie, s'étendant sur des centaines d'hectares le long du bord de mer.",
        burgas_garden_details_p2: "Le parc abrite de nombreux monuments de personnalités éminentes, des plantes exotiques, le Théâtre d'été et le centre culturel 'Sea Casino'. C'est l'endroit idéal pour la marche, le sport et la détente.",
        burgas_sand_details_title: "La Magie des Sculptures de Sable",
        burgas_sand_details_p1: "Chaque été, Bourgas devient la scène de l'un des événements les plus impressionnants de Bulgarie – le Festival des Sculptures de Sable.",
        burgas_sand_details_p2: "Des maîtres du monde entier utilisent des milliers de tonnes de sable spécial pour sculpter des personnages de contes de fées, de films et de l'histoire. L'exposition est située dans le parc 'Ezero' et est ouverte pendant toute la saison estivale.",
        burgas_port_details_title: "Port de Bourgas – Porte sur le Monde",
        burgas_port_details_p1: "Le port de Bourgas n'est pas seulement un centre économique, mais aussi l'une des zones de loisirs les plus modernes de Bulgarie.",
        burgas_port_details_p2: "La zone d'accès public comprend le 'Magazia 1' rénové, la gare maritime et l'emblématique phare. Ici, vous pourrez profiter d'un magnifique panorama marin, de restaurants et d'événements culturels.",
        treasures_page_title: "Trésors de Bulgarie",
        treasures_page_desc: "Les terres bulgares ont préservé d'incroyables trésors d'or et d'argent, qui figurent aujourd'hui parmi les pièces les plus précieuses des musées du monde.",
        treasure_pan_title: "Panagyurishte Gold Treasure",
        treasure_pan_short: "L'un des trésors thraces les plus célèbres au monde. Il se compose de 9 récipients en or pur (plus de 6 kg).",
        treasure_pan_p1: "Le trésor d'or de Panagyurishte est le trésor thrace le plus célèbre au monde. Il a été découvert le 8 décembre 1949 par trois frères - Pavel, Petko et Mihail Deykovi, lors de fouilles près de la ville de Panagyurishte.",
        treasure_pan_p2: "Le trésor se compose de 9 récipients en or pur (23 carats) d'un poids total de 6,164 kg. L'ensemble comprend une phiale et huit rhytons, décorés de scènes extrêmement complexes et détaillées de la mythologie antique.",
        treasure_pan_desc_title: "Description des récipients :",
        treasure_pan_p3: "Le récipient central est une amphore-rhyton dont les anses ont la forme de centaures en lutte. D'autres rhytons représentent des têtes d'animaux (bélier, cerf) et de déesses (Athéna, Héra, Aphrodite).",
        treasure_pan_p4: "On suppose que le trésor appartenait à un souverain odryse de la fin du IVe ou du début du IIIe siècle av. J.-C. Il était utilisé à des fins rituelles et lors de festins, démontrant la richesse et la haute culture des Thraces.",
        treasure_var_title: "Varna Gold Treasure",
        treasure_var_short: "C'est l'or travaillé le plus ancien au monde, datant de plus de 6 000 ans.",
        treasure_var_p1: "Le trésor d'or de Varna est l'or technologiquement traité le plus ancien au monde. Il a été découvert en 1972 lors de fouilles archéologiques dans la nécropole chalcolithique de Varna.",
        treasure_var_p2: "La découverte date de la fin du 5e millénaire av. J.-C. (il y a plus de 6 000 ans). Le trésor comprend plus de 3 000 objets en or d'un poids total d'environ 6 kg, ce qui est une quantité exceptionnelle pour l'époque.",
        treasure_var_desc_title: "Importance historique :",
        treasure_var_p3: "Le trésor de Varna prouve l'existence d'une civilisation très développée sur la côte de la mer Noire, appelée « Culture de Varna ». Cette civilisation connaissait des processus métallurgiques complexes et avait une hiérarchie sociale clairement définie.",
        treasure_var_p4: "La tombe la plus célèbre (n° 43) contient les restes d'un homme, probablement un souverain ou un prêtre, enterré avec plus de 1,5 kg d'objets en or, dont un sceptre en or - symbole de pouvoir.",
        treasure_rog_title: "Rogozen Treasure",
        treasure_rog_short: "Le plus grand trésor thrace en volume, composé de 165 récipients en argent.",
        treasure_rog_p1: "Le trésor de Rogozen est le plus grand trésor thrace en volume jamais découvert. Il a été découvert par hasard en 1985-1986 dans le village de Rogozen, dans la région de Vratsa.",
        treasure_rog_p2: "Le trésor se compose de 165 récipients en argent, dont certains sont dorés. Leur poids total est de près de 20 kg. La collection comprend des phiales, des cruches et un skyphos.",
        treasure_rog_p3: "Les récipients sont décorés de riches scènes en relief représentant des divinités thraces, des scènes de chasse et des créatures mythologiques. De nombreux objets portent des inscriptions avec les noms de souverains et d'artisans thraces.",
        treasure_val_title: "Valchitrun Gold Treasure",
        treasure_val_short: "Composé de 13 objets en or d'un poids total de 12,5 kg. L'un des plus massifs d'Europe.",
        treasure_val_p1: "Le trésor d'or de Valchitrun est l'un des trésors les plus mystérieux et les plus massifs au monde. Il a été découvert en 1924 dans le village de Valchitrun, dans la région de Pleven.",
        treasure_val_p2: "Le trésor se compose de 13 objets en or d'un poids total de 12,5 kg d'or pur. Le plus impressionnant est le grand canthare (récipient à vin) à deux anses, qui pèse plus de 4 kg.",
        treasure_val_p3: "Les objets datent de la fin de l'âge du bronze (XIVe-XIIIe siècle av. J.-C.). Ils étaient utilisés pour des rituels religieux par les prêtres-rois thraces.",
        back_to_treasures: "Retour aux trésors",
        btn_read_more: "En savoir plus",
        pgmee_hero_subtitle: "Connaissance, professionnalisme, avenir",
        pgmee_about_title: "À propos de l'école",
        pgmee_about_desc: "Le Lycée Professionnel de Génie Mécanique, Électrotechnique et Électronique (PGMEE) est l'un des établissements d'enseignement les plus prestigieux de la ville de Bourgas. Avec une longue histoire et des méthodes d'enseignement innovantes, nous préparons la prochaine génération d'ingénieurs et de spécialistes techniques.",
        pgmee_stat1_val: "100+",
        pgmee_stat1_label: "Années d'expérience",
        pgmee_stat2_val: "900+",
        pgmee_stat2_label: "Élèves",
        pgmee_specialties_title: "Spécialités",
        pgmee_spec1_title: "Transport Automobile",
        pgmee_spec1_desc: "Diagnostic et réparation modernes de voitures.",
        pgmee_spec2_title: "Électronique",
        pgmee_spec2_desc: "Conception et maintenance de systèmes électroniques.",
        pgmee_spec3_title: "Mécatronique",
        pgmee_spec3_desc: "L'avenir de l'automatisation et de la robotique.",
        pgmee_success_title: "Nos Succès",
        pgmee_success1_title: "Concours Nationaux",
        pgmee_success1_desc: "Nombreuses premières places et médailles d'or dans des concours d'électronique et de mécanique.",
        pgmee_success2_title: "Partenariats",
        pgmee_success2_desc: "Coopération réussie avec des entreprises leaders de l'industrie pour la formation en alternance.",
        pgmee_success3_title: "Innovations",
        pgmee_success3_desc: "Brevets propres et développements innovants de nos étudiants dans le domaine de la robotique."
    },
    zh: {
        nav_home: "首页",
        nav_history: "历史",
        nav_treasures: "宝藏",
        nav_dates: "重要日期",
        hero_title: "保加利亚",
        history_title: "历史",
        history_desc: "保加利亚拥有跨越数千年的丰富而古老的历史。从古色雷斯人到现代国家，每个时代都留下了烙印。",
        treasures_title: "宝藏",
        treasures_desc: "保加利亚拥有世界上一些最令人印象深刻的古代宝藏，揭示了古代文明的伟大。",
        btn_learn_more: "了解更多",
        btn_discover_more: "发现更多",
        back_to_home: "返回首页",
        history_page_title: "保加利亚历史",
        dates_page_title: "重要日期",
        burgas_hero_tagline: "海洋、鸟类和节日的城市",
        burgas_welcome_title: "欢迎来到布尔加斯",
        burgas_welcome_desc: "布尔加斯是保加利亚第四大城市，位于美丽的黑海沿岸。该市以其海洋公园、沙雕节和待客热情而闻名，是放松和文化体验的完美目的地。",
        burgas_card_garden_title: "海洋公园",
        burgas_card_garden_desc: "保加利亚最大、最美丽的公园之一，沿着海岸延伸。",
        burgas_card_sand_title: "沙雕",
        burgas_card_sand_desc: "一年一度的节日，汇集了来自世界各地的艺术家，他们用沙子创作杰作。",
        burgas_card_port_title: "布尔加斯港",
        burgas_card_port_desc: "现代化的休闲区，拥有灯塔、餐厅和散步场所。",
        back_to_burgas: "返回布尔加斯",
        burgas_history_page_title: "布尔加斯历史",
        burgas_history_p1: "布尔加斯的历史可以追溯到几千年前，该地区最早的定居点可以追溯到色雷斯人时期。Aquae Calidae 古老的治疗泉水自古以来就吸引着游客，包括罗马皇帝和拜占庭统治者。",
        burgas_history_p2: "在中世纪，该地区是一个重要的战略点，但该市真正的繁荣始于 19 世纪末和 20 世纪初。港口的建设使布尔加斯成为黑海南部沿岸的主要商业和经济中心。",
        burgas_history_p3: "今天，布尔加斯是一座现代化的欧洲城市，它保留了其文化遗产，同时大胆地展望未来，成为世界级的节日和旅游中心。",
        burgas_garden_details_title: "海洋公园 – 城市的心脏",
        burgas_garden_details_p1: "海洋公园是布尔加斯的肺。它是保加利亚最大、最美丽的公园之一，沿着海岸延伸数百英亩。",
        burgas_garden_details_p2: "公园里有许多杰出人物的纪念碑、异国植物、露天剧场和“海上赌场”文化中心。这里是散步、运动和放松的理想场所。",
        burgas_sand_details_title: "沙雕的魔力",
        burgas_sand_details_p1: "每年夏天，布尔加斯都会成为保加利亚最令人印象深刻的活动之一——沙雕节的舞台。",
        burgas_sand_details_p2: "来自世界各地的艺术大师使用数千吨特种沙子雕刻童话、电影和历史人物。展览位于“Ezero”公园，整个夏季开放。",
        burgas_port_details_title: "布尔加斯港 – 通往世界的门户",
        burgas_port_details_p1: "布尔加斯港不仅是一个经济枢纽，也是保加利亚最现代化的休闲区之一。",
        burgas_port_details_p2: "公共进入区包括翻新的“Magazia 1”、海运站和标志性的灯塔。在这里，您可以欣赏到美丽的海景、餐厅和文化活动。",
        treasures_page_title: "保加利亚的宝藏",
        treasures_page_desc: "保加利亚土地上保存着令人难以置信的金银财宝，这些珍宝如今已成为世界各大博物馆中最珍贵的展品之一。",
        treasure_pan_title: "Panagyurishte Gold Treasure",
        treasure_pan_short: "世界上最著名的色雷斯宝藏之一。它由9件纯金器皿组成（超过6公斤）。",
        treasure_pan_p1: "帕纳久里什泰金宝藏是世界上最著名的色雷斯宝藏。它于1949年12月8日由帕维尔、佩特科和米哈伊尔·德伊科夫三兄弟在帕纳久里什泰镇附近的挖掘工作中发现。",
        treasure_pan_p2: "该宝藏由9件纯金（23K）器皿组成，总重6.164公斤。这套器皿包括一个扁平底杯和八个角杯，装饰有极其复杂细致的古代神话场景。",
        treasure_pan_desc_title: "器皿描述：",
        treasure_pan_p3: "中心器皿是一个双耳角杯，其手柄形状为搏斗的半人马。其他角杯描绘了动物（公羊、鹿）和女神（雅典娜、赫拉、阿佛洛狄忒）的头部。",
        treasure_pan_p4: "据推测，该宝藏是公元前4世纪末或公元前3世纪初一位奥德里西亚统治者的财产。它被用于仪式和宴会，展示了色雷斯人的财富和高度文化。",
        treasure_var_title: "Varna Gold Treasure",
        treasure_var_short: "这是世界上最古老的加工黄金，距今已有6000多年的历史。",
        treasure_var_p1: "瓦尔纳金宝藏是世界上最古老的经过技术加工的黄金。它于1972年在瓦尔纳铜石并用时代墓地的考古发掘中被发现。",
        treasure_var_p2: "这一发现可以追溯到公元前5000年末（距今已有6000多年）。该宝藏包括3000多件金器，总重约6公斤，在那个时代可谓数量惊人。",
        treasure_var_desc_title: "历史意义：",
        treasure_var_p3: "瓦尔纳宝藏证明了在黑海沿岸存在一个高度发达的文明，被称为“瓦尔纳文化”。这个文明掌握了复杂的冶金工艺，并拥有明确的社会等级制度。",
        treasure_var_p4: "最著名的墓葬（43号墓）包含一名男子的遗骸，可能是统治者或祭司，与超过1.5公斤的金器一起埋葬，其中包括一根金权杖——权力的象征。",
        treasure_rog_title: "Rogozen Treasure",
        treasure_rog_short: "体积最大的色雷斯宝藏，由165件银器组成。",
        treasure_rog_p1: "罗戈曾宝藏是有史以来发现的体积最大的色雷斯宝藏。它于1985年至1986年在弗拉察地区的罗戈曾村被偶然发现。",
        treasure_rog_p2: "该宝藏由165件银器组成，其中一些是镀金的。它们的总重量接近20公斤。这批收藏品包括扁平底杯、水壶和一个大口杯。",
        treasure_rog_p3: "这些器皿装饰有丰富的浮雕场景，描绘了色雷斯神灵、狩猎场景和神话生物。许多物品上刻有色雷斯统治者和工匠的名字。",
        treasure_val_title: "Valchitrun Gold Treasure",
        treasure_val_short: "由13件金器组成，总重12.5公斤。欧洲最庞大的金器群之一。",
        treasure_val_p1: "沃尔奇特伦金宝藏是世界上最神秘和最庞大的宝藏之一。它于1924年在普列文地区的沃尔奇特伦村被发现。",
        treasure_val_p2: "该宝藏由13件金器组成，纯金总重12.5公斤。最令人印象深刻的是带有两个把手的大酒杯，重达4公斤以上。",
        treasure_val_p3: "这些物品可以追溯到青铜时代晚期（公元前14-13世纪）。它们被色雷斯祭司国王用于宗教仪式。",
        back_to_treasures: "返回宝藏",
        btn_read_more: "阅读更多",
        pgmee_hero_subtitle: "知识、专业、未来",
        pgmee_about_title: "关于学校",
        pgmee_about_desc: "布尔加斯机械与电气工程和电子职业高中 (PGMEE) 是布尔加斯市最著名的教育机构之一。凭借悠久的历史和创新的教学方法，我们培养下一代工程师和技术专家。",
        pgmee_stat1_val: "100+",
        pgmee_stat1_label: "多年经验",
        pgmee_stat2_val: "900+",
        pgmee_stat2_label: "学生",
        pgmee_specialties_title: "专业",
        pgmee_spec1_title: "汽车运输",
        pgmee_spec1_desc: "现代化的汽车诊断和维修。",
        pgmee_spec2_title: "电子学",
        pgmee_spec2_desc: "电子系统的设计和维护。",
        pgmee_spec3_title: "机电一体化",
        pgmee_spec3_desc: "自动化和机器人技术的未来。",
        pgmee_success_title: "我们的成就",
        pgmee_success1_title: "全国竞赛",
        pgmee_success1_desc: "在电子和机械竞赛中获得众多名次和金牌。",
        pgmee_success2_title: "合作伙伴",
        pgmee_success2_desc: "与行业领先公司成功合作，开展双元制教育。",
        pgmee_success3_title: "创新",
        pgmee_success3_desc: "我们的学生在机器人领域的专利和创新开发。"
    }
};

function setLanguage(lang) {
    if (!translations[lang]) return;
    localStorage.setItem("selectedLang", lang);

    document.querySelectorAll("[data-i18n]").forEach(el => {
        const key = el.getAttribute("data-i18n");
        if (translations[lang][key]) {
            el.textContent = translations[lang][key];
        }
    });

    const logo = document.querySelector(".logo");
    if (logo) {
        if (lang === "bg") logo.textContent = "България";
        else logo.textContent = "Bulgaria";
    }

    if (langOptions) langOptions.classList.remove("active");
}

document.querySelectorAll(".lang-option").forEach(opt => {
    opt.addEventListener("click", () => {
        setLanguage(opt.getAttribute("data-lang"));
    });
});

window.addEventListener("DOMContentLoaded", () => {
    const savedLang = localStorage.getItem("selectedLang") || "bg";
    setLanguage(savedLang);
});
